[2024-11-26T00:14:27.314+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:14:27.322+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:14:27.352+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:14:27.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:14:27.382+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:14:27.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:14:27.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:14:27.569+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.312 seconds
[2024-11-26T00:14:57.984+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:14:57.986+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:14:57.991+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:14:57.990+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:14:57.995+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:14:57.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:14:57.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:14:58.034+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.058 seconds
[2024-11-26T00:15:28.164+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:15:28.169+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:15:28.172+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:15:28.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:15:28.178+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:15:28.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:15:28.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:15:28.217+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.067 seconds
[2024-11-26T00:15:58.811+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:15:58.812+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:15:58.815+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:15:58.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:15:58.819+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:15:58.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:15:58.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:15:58.844+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.039 seconds
[2024-11-26T00:16:28.969+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:16:28.973+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:16:28.976+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:16:28.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:16:28.980+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:16:28.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:16:28.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:16:29.006+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.044 seconds
[2024-11-26T00:16:59.504+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:16:59.506+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:16:59.508+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:16:59.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:16:59.512+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:16:59.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:16:59.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:16:59.541+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.042 seconds
[2024-11-26T00:17:29.575+0000] {processor.py:186} INFO - Started process (PID=546) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:17:29.577+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:17:29.580+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:17:29.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:17:29.584+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:17:29.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:17:29.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:17:29.612+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.044 seconds
[2024-11-26T00:17:59.768+0000] {processor.py:186} INFO - Started process (PID=683) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:17:59.769+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:17:59.772+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:17:59.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:17:59.776+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:17:59.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:17:59.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:17:59.801+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.039 seconds
[2024-11-26T00:18:30.338+0000] {processor.py:186} INFO - Started process (PID=741) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:18:30.340+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:18:30.343+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:18:30.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:18:30.348+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:18:30.347+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:18:30.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:18:30.418+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.088 seconds
[2024-11-26T00:19:01.067+0000] {processor.py:186} INFO - Started process (PID=881) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:19:01.072+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:19:01.076+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:19:01.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:19:01.081+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:19:01.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:19:01.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:19:01.114+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.054 seconds
[2024-11-26T00:19:31.144+0000] {processor.py:186} INFO - Started process (PID=939) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:19:31.146+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:19:31.149+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:19:31.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:19:31.153+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:19:31.152+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:19:31.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:19:31.191+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.053 seconds
[2024-11-26T00:20:01.385+0000] {processor.py:186} INFO - Started process (PID=997) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:20:01.386+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:20:01.390+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:20:01.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:20:01.394+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:20:01.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:20:01.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:20:01.423+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.044 seconds
[2024-11-26T00:20:31.555+0000] {processor.py:186} INFO - Started process (PID=1055) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:20:31.559+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:20:31.564+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:20:31.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:20:31.569+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:20:31.567+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:20:31.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:20:31.598+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.052 seconds
[2024-11-26T00:21:02.267+0000] {processor.py:186} INFO - Started process (PID=1113) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:21:02.271+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:21:02.274+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:21:02.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:21:02.277+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:21:02.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:21:02.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:21:02.301+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.040 seconds
[2024-11-26T00:21:32.554+0000] {processor.py:186} INFO - Started process (PID=1171) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:21:32.558+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:21:32.561+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:21:32.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:21:32.566+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:21:32.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:21:32.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:21:32.592+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.044 seconds
[2024-11-26T00:22:02.719+0000] {processor.py:186} INFO - Started process (PID=1229) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:22:02.723+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:22:02.728+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:22:02.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:22:02.732+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:22:02.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:22:02.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:22:02.768+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.057 seconds
[2024-11-26T00:22:33.441+0000] {processor.py:186} INFO - Started process (PID=1287) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:22:33.445+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:22:33.448+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:22:33.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:22:33.452+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:22:33.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:22:33.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:22:33.482+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.049 seconds
[2024-11-26T00:23:03.921+0000] {processor.py:186} INFO - Started process (PID=1345) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:23:03.923+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:23:03.928+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:23:03.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:23:03.934+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:23:03.932+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:23:03.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:23:03.969+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.057 seconds
[2024-11-26T00:23:54.081+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:23:54.083+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:23:54.089+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:23:54.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:23:54.098+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:23:54.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:23:54.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:23:54.143+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.076 seconds
[2024-11-26T00:24:24.361+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:24:24.366+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:24:24.370+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:24:24.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:24:24.378+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:24:24.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:24:24.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:24:24.433+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.084 seconds
[2024-11-26T00:24:55.138+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:24:55.142+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:24:55.144+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:24:55.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:24:55.147+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:24:55.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:24:55.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:24:55.176+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.045 seconds
[2024-11-26T00:25:25.502+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:25:25.507+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:25:25.510+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:25:25.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:25:25.513+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:25:25.512+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:25:25.514+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:25:25.543+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.049 seconds
[2024-11-26T00:25:55.841+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:25:55.845+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:25:55.848+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:25:55.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:25:55.851+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:25:55.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:25:55.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:25:55.876+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.040 seconds
[2024-11-26T00:26:26.195+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:26:26.200+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:26:26.203+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:26:26.203+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:26:26.207+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:26:26.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:26:26.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:26:26.237+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.049 seconds
[2024-11-26T00:26:56.335+0000] {processor.py:186} INFO - Started process (PID=465) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:26:56.339+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:26:56.342+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:26:56.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:26:56.346+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:26:56.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:26:56.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:26:56.370+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.040 seconds
[2024-11-26T00:27:26.599+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:27:26.600+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:27:26.604+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:27:26.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:27:26.607+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:27:26.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:27:26.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:27:26.635+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.044 seconds
[2024-11-26T00:27:57.347+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:27:57.349+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:27:57.351+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:27:57.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:27:57.354+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:27:57.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:27:57.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:27:57.378+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.037 seconds
[2024-11-26T00:28:27.431+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:28:27.436+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:28:27.440+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:28:27.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:28:27.445+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:28:27.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:28:27.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:28:27.476+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.054 seconds
[2024-11-26T00:28:57.814+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:28:57.816+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:28:57.818+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:28:57.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:28:57.824+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:28:57.822+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:28:57.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:28:57.857+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.051 seconds
[2024-11-26T00:29:28.030+0000] {processor.py:186} INFO - Started process (PID=755) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:29:28.035+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:29:28.037+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:29:28.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:29:28.040+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:29:28.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:29:28.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:29:28.067+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.043 seconds
[2024-11-26T00:29:58.455+0000] {processor.py:186} INFO - Started process (PID=813) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:29:58.457+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:29:58.459+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:29:58.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:29:58.463+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:29:58.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:29:58.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:29:58.487+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.038 seconds
[2024-11-26T00:30:28.836+0000] {processor.py:186} INFO - Started process (PID=871) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:30:28.838+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:30:28.840+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:30:28.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:30:28.843+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:30:28.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:30:28.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:30:28.868+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.038 seconds
[2024-11-26T00:30:58.910+0000] {processor.py:186} INFO - Started process (PID=929) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:30:58.915+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:30:58.917+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:30:58.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:30:58.922+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:30:58.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:30:58.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:30:58.950+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.046 seconds
[2024-11-26T00:31:29.276+0000] {processor.py:186} INFO - Started process (PID=987) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:31:29.278+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:31:29.281+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:31:29.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:31:29.286+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:31:29.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:31:29.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:31:29.317+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.047 seconds
[2024-11-26T00:31:59.772+0000] {processor.py:186} INFO - Started process (PID=1045) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:31:59.777+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:31:59.780+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:31:59.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:31:59.784+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:31:59.783+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:31:59.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:31:59.814+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.054 seconds
[2024-11-26T00:32:30.549+0000] {processor.py:186} INFO - Started process (PID=1103) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:32:30.551+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:32:30.554+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:32:30.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:32:30.559+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:32:30.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:32:30.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:32:30.594+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.055 seconds
[2024-11-26T00:33:01.070+0000] {processor.py:186} INFO - Started process (PID=1161) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:33:01.074+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:33:01.077+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:33:01.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:33:01.081+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:33:01.079+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:33:01.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:33:01.114+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.050 seconds
[2024-11-26T00:33:31.316+0000] {processor.py:186} INFO - Started process (PID=1219) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:33:31.321+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:33:31.325+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:33:31.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:33:31.331+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:33:31.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:33:31.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:33:31.365+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.060 seconds
[2024-11-26T00:34:02.147+0000] {processor.py:186} INFO - Started process (PID=1277) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:34:02.152+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:34:02.155+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:34:02.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:34:02.158+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:34:02.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:34:02.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:34:02.184+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.043 seconds
[2024-11-26T00:34:32.313+0000] {processor.py:186} INFO - Started process (PID=1335) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:34:32.314+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:34:32.318+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:34:32.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:34:32.322+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:34:32.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:34:32.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:34:32.352+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.048 seconds
[2024-11-26T00:35:03.019+0000] {processor.py:186} INFO - Started process (PID=1393) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:35:03.021+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:35:03.023+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:35:03.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:35:03.027+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:35:03.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:35:03.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:35:03.052+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.039 seconds
[2024-11-26T00:35:33.895+0000] {processor.py:186} INFO - Started process (PID=1451) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:35:33.897+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:35:33.902+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:35:33.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:35:33.908+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:35:33.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:35:33.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:35:33.944+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.061 seconds
[2024-11-26T00:36:04.093+0000] {processor.py:186} INFO - Started process (PID=1509) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:36:04.097+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:36:04.100+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:36:04.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:36:04.106+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:36:04.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:36:04.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:36:04.138+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.054 seconds
[2024-11-26T00:36:34.347+0000] {processor.py:186} INFO - Started process (PID=1567) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:36:34.349+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:36:34.353+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:36:34.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:36:34.358+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:36:34.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:36:34.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:36:34.389+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.051 seconds
[2024-11-26T00:37:04.914+0000] {processor.py:186} INFO - Started process (PID=1625) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:37:04.915+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:37:04.918+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:37:04.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:37:04.922+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:37:04.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:37:04.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:37:04.953+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.047 seconds
[2024-11-26T00:37:35.481+0000] {processor.py:186} INFO - Started process (PID=1683) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:37:35.483+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:37:35.486+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:37:35.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:37:35.491+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:37:35.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:37:35.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:37:35.522+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.050 seconds
[2024-11-26T00:38:06.165+0000] {processor.py:186} INFO - Started process (PID=1740) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:38:06.166+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:38:06.170+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:38:06.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:38:06.177+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:38:06.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:38:06.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:38:06.222+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.069 seconds
[2024-11-26T00:38:36.933+0000] {processor.py:186} INFO - Started process (PID=1796) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:38:36.937+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:38:36.940+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:38:36.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:38:36.944+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:38:36.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:38:36.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:38:36.973+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.047 seconds
[2024-11-26T00:39:07.534+0000] {processor.py:186} INFO - Started process (PID=1854) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:39:07.536+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:39:07.539+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:39:07.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:39:07.544+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:39:07.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:39:07.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:39:07.573+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.048 seconds
[2024-11-26T00:39:38.338+0000] {processor.py:186} INFO - Started process (PID=1912) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:39:38.339+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:39:38.343+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:39:38.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:39:38.348+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:39:38.347+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:39:38.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:39:38.379+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.050 seconds
[2024-11-26T00:40:09.068+0000] {processor.py:186} INFO - Started process (PID=1967) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:40:09.070+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:40:09.072+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:40:09.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:40:09.077+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:40:09.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:40:09.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:40:09.103+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.042 seconds
[2024-11-26T00:40:39.639+0000] {processor.py:186} INFO - Started process (PID=2020) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:40:39.640+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:40:39.643+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:40:39.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:40:39.647+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:40:39.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:40:39.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:40:39.673+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.041 seconds
[2024-11-26T00:41:11.107+0000] {processor.py:186} INFO - Started process (PID=2075) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:41:11.109+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:41:11.113+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:41:11.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:41:11.116+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:41:11.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:41:11.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:41:11.139+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.039 seconds
[2024-11-26T00:41:41.301+0000] {processor.py:186} INFO - Started process (PID=2121) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:41:41.303+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:41:41.305+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:41:41.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:41:41.309+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:41:41.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:41:41.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:41:41.334+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.039 seconds
[2024-11-26T00:42:11.567+0000] {processor.py:186} INFO - Started process (PID=2179) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:42:11.568+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:42:11.572+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:42:11.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:42:11.576+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:42:11.574+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:42:11.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:42:11.602+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.042 seconds
[2024-11-26T00:42:42.098+0000] {processor.py:186} INFO - Started process (PID=2237) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:42:42.099+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:42:42.101+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:42:42.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:42:42.106+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:42:42.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:42:42.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:42:42.131+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.039 seconds
[2024-11-26T00:43:12.280+0000] {processor.py:186} INFO - Started process (PID=2295) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:43:12.284+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:43:12.286+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:43:12.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:43:12.290+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:43:12.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:43:12.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:43:12.314+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.040 seconds
[2024-11-26T00:43:43.167+0000] {processor.py:186} INFO - Started process (PID=2353) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:43:43.172+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:43:43.175+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:43:43.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:43:43.179+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:43:43.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:43:43.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:43:43.205+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.045 seconds
[2024-11-26T00:44:13.329+0000] {processor.py:186} INFO - Started process (PID=2411) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:44:13.330+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:44:13.333+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:44:13.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:44:13.337+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:44:13.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:44:13.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:44:13.363+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.039 seconds
[2024-11-26T00:44:43.804+0000] {processor.py:186} INFO - Started process (PID=2469) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:44:43.806+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:44:43.809+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:44:43.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:44:43.812+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:44:43.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:44:43.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:44:43.840+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.044 seconds
[2024-11-26T00:45:14.144+0000] {processor.py:186} INFO - Started process (PID=2527) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:45:14.147+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:45:14.152+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:45:14.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:45:14.159+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:45:14.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:45:14.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:45:14.231+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.098 seconds
[2024-11-26T00:46:35.823+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:46:35.827+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:46:35.831+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:46:35.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:46:35.840+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:46:35.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:46:35.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:46:35.892+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.081 seconds
[2024-11-26T00:47:06.397+0000] {processor.py:186} INFO - Started process (PID=178) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:47:06.402+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:47:06.406+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:47:06.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:47:06.412+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:47:06.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:47:06.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:47:06.447+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.063 seconds
[2024-11-26T00:47:36.804+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:47:36.810+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:47:36.814+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:47:36.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:47:36.823+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:47:36.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:47:36.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:47:36.867+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.075 seconds
[2024-11-26T00:48:06.934+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:48:06.935+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:48:06.939+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:48:06.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:48:06.943+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:48:06.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:48:06.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:48:06.969+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.041 seconds
[2024-11-26T00:48:37.594+0000] {processor.py:186} INFO - Started process (PID=352) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:48:37.597+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:48:37.604+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:48:37.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:48:37.609+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:48:37.607+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:48:37.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:48:37.642+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.058 seconds
[2024-11-26T00:49:08.538+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:49:08.542+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:49:08.545+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:49:08.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:49:08.549+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:49:08.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:49:08.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:49:08.573+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.043 seconds
[2024-11-26T00:49:38.975+0000] {processor.py:186} INFO - Started process (PID=468) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:49:38.976+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:49:38.978+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:49:38.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:49:38.982+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:49:38.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:49:38.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:49:39.006+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.037 seconds
[2024-11-26T00:50:09.292+0000] {processor.py:186} INFO - Started process (PID=526) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:50:09.294+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:50:09.297+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:50:09.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:50:09.303+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:50:09.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:50:09.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:50:09.340+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.059 seconds
[2024-11-26T00:50:39.923+0000] {processor.py:186} INFO - Started process (PID=584) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:50:39.925+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:50:39.929+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:50:39.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:50:39.937+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:50:39.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:50:39.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:50:39.985+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.077 seconds
[2024-11-26T00:51:10.673+0000] {processor.py:186} INFO - Started process (PID=642) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:10.677+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:51:10.681+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:51:10.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:10.686+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:51:10.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:51:10.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:10.720+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.052 seconds
[2024-11-26T00:51:41.348+0000] {processor.py:186} INFO - Started process (PID=700) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:41.353+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:51:41.356+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:51:41.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:41.361+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:51:41.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 2, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:51:41.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:41.394+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.055 seconds
[2024-11-26T00:51:45.181+0000] {processor.py:186} INFO - Started process (PID=713) to work on /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:45.182+0000] {processor.py:914} INFO - Processing file /opt/bitnami/airflow/dags/teste_conn.py for tasks to queue
[2024-11-26T00:51:45.185+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:51:45.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:45.189+0000] {logging_mixin.py:190} INFO - [2024-11-26T00:51:45.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/bitnami/airflow/dags/teste_conn.py
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bitnami/airflow/dags/teste_conn.py", line 11, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache.spark'
[2024-11-26T00:51:45.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/bitnami/airflow/dags/teste_conn.py
[2024-11-26T00:51:45.214+0000] {processor.py:208} INFO - Processing /opt/bitnami/airflow/dags/teste_conn.py took 0.040 seconds
